package org.gaziz.birgram.core.telegram.chats.impl

import org.drinkless.tdlib.TdApi

fun TdApi.Chat.copy(
    id: Long = this.id,
    type: TdApi.ChatType = this.type,
    title: String = this.title,
    photo: TdApi.ChatPhotoInfo? = this.photo,
    accentColorId: Int = this.accentColorId,
    backgroundCustomEmojiId: Long = this.backgroundCustomEmojiId,
    upgradedGiftColors: TdApi.UpgradedGiftColors? = this.upgradedGiftColors,
    profileAccentColorId: Int = this.profileAccentColorId,
    profileBackgroundCustomEmojiId: Long = this.profileBackgroundCustomEmojiId,
    permissions: TdApi.ChatPermissions = this.permissions,
    lastMessage: TdApi.Message? = this.lastMessage,
    positions: Array<TdApi.ChatPosition> = this.positions,
    chatLists: Array<TdApi.ChatList> = this.chatLists,
    messageSenderId: TdApi.MessageSender? = this.messageSenderId,
    blockList: TdApi.BlockList? = this.blockList,
    hasProtectedContent: Boolean = this.hasProtectedContent,
    isTranslatable: Boolean = this.isTranslatable,
    isMarkedAsUnread: Boolean = this.isMarkedAsUnread,
    viewAsTopics: Boolean = this.viewAsTopics,
    hasScheduledMessages: Boolean = this.hasScheduledMessages,
    canBeDeletedOnlyForSelf: Boolean = this.canBeDeletedOnlyForSelf,
    canBeDeletedForAllUsers: Boolean = this.canBeDeletedForAllUsers,
    canBeReported: Boolean = this.canBeReported,
    defaultDisableNotification: Boolean = this.defaultDisableNotification,
    unreadCount: Int = this.unreadCount,
    lastReadInboxMessageId: Long = this.lastReadInboxMessageId,
    lastReadOutboxMessageId: Long = this.lastReadOutboxMessageId,
    unreadMentionCount: Int = this.unreadMentionCount,
    unreadReactionCount: Int = this.unreadReactionCount,
    notificationSettings: TdApi.ChatNotificationSettings = this.notificationSettings,
    availableReactions: TdApi.ChatAvailableReactions = this.availableReactions,
    messageAutoDeleteTime: Int = this.messageAutoDeleteTime,
    emojiStatus: TdApi.EmojiStatus? = this.emojiStatus,
    background: TdApi.ChatBackground? = this.background,
    theme: TdApi.ChatTheme? = this.theme,
    actionBar: TdApi.ChatActionBar? = this.actionBar,
    businessBotManageBar: TdApi.BusinessBotManageBar? = this.businessBotManageBar,
    videoChat: TdApi.VideoChat? = this.videoChat,
    pendingJoinRequests: TdApi.ChatJoinRequestsInfo? = this.pendingJoinRequests,
    replyMarkupMessageId: Long = this.replyMarkupMessageId,
    draftMessage: TdApi.DraftMessage? = this.draftMessage,
    clientData: String = this.clientData
): TdApi.Chat {
    return TdApi.Chat(
        id,
        type,
        title,
        photo,
        accentColorId,
        backgroundCustomEmojiId,
        upgradedGiftColors,
        profileAccentColorId,
        profileBackgroundCustomEmojiId,
        permissions,
        lastMessage,
        positions,
        chatLists,
        messageSenderId,
        blockList,
        hasProtectedContent,
        isTranslatable,
        isMarkedAsUnread,
        viewAsTopics,
        hasScheduledMessages,
        canBeDeletedOnlyForSelf,
        canBeDeletedForAllUsers,
        canBeReported,
        defaultDisableNotification,
        unreadCount,
        lastReadInboxMessageId,
        lastReadOutboxMessageId,
        unreadMentionCount,
        unreadReactionCount,
        notificationSettings,
        availableReactions,
        messageAutoDeleteTime,
        emojiStatus,
        background,
        theme,
        actionBar,
        businessBotManageBar,
        videoChat,
        pendingJoinRequests,
        replyMarkupMessageId,
        draftMessage,
        clientData
    )
}

fun TdApi.ChatPhotoInfo.copy(
    small: TdApi.File = this.small,
    big: TdApi.File = this.big,
    miniThumbnail: TdApi.Minithumbnail? = this.minithumbnail,
    hasAnimation: Boolean = this.hasAnimation,
    isPersonal: Boolean = this.isPersonal
): TdApi.ChatPhotoInfo {
    return TdApi.ChatPhotoInfo(
        small,
        big,
        miniThumbnail,
        hasAnimation,
        isPersonal
    )
}